In [2]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
%matplotlib inline

In [4]:
a1=np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [5]:
a1.shape

(4,)

In [6]:
a2=np.array([[1,2,3,4]])

In [7]:
a2

array([[1, 2, 3, 4]])

In [8]:
a2.shape

(1, 4)

In [9]:
a3=np.array([[1],[2],[3],[4]])
a3.shape

(4, 1)

In [10]:
M1 = np.array([[1,0,0],[0,1,0],[0,0,1],[0,0,1]])

In [11]:
M1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [12]:
np.random.seed(42)

In [13]:
np

<module 'numpy' from 'C:\\Users\\hmani\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [19]:
df=pd.read_csv('input.csv')

In [20]:
import io

In [21]:
print(df)

   id    name    salary  start_date        dept
0   1    Rick  62323.30  2012-01-01          IT
1   2     Dan  54315.20  2013-09-23  Operations
2   3   Tusar  61421.00  2014-11-15          IT
3   4    Ryan  72439.00  2014-05-11          HR
4   5    Gary  84533.25  2015-03-27     Finance
5   6   Rasmi  57638.00  2013-05-21          IT
6   7  Pranab  63242.80  2013-07-30  Operations
7   8    Guru  72422.50  2014-06-17     Finance


In [3]:
M2=np.array([["harsh","elder",20],["Achu","middle",19],["Sachu","youngest",16]])

In [4]:
M2

array([['harsh', 'elder', '20'],
       ['Achu', 'middle', '19'],
       ['Sachu', 'youngest', '16']], dtype='<U11')

In [5]:
df2=pd.DataFrame(M2,columns=["Name","order","Age"])

In [6]:
df2

Name     order Age
0  harsh     elder  20
1   Achu    middle  19
2  Sachu  youngest  16

In [7]:
df3=pd.read_csv('input.csv')

In [8]:
df3

id    name    salary  start_date        dept
0   1    Rick  62323.30  2012-01-01          IT
1   2     Dan  54315.20  2013-09-23  Operations
2   3   Tusar  61421.00  2014-11-15          IT
3   4    Ryan  72439.00  2014-05-11          HR
4   5    Gary  84533.25  2015-03-27     Finance
5   6   Rasmi  57638.00  2013-05-21          IT
6   7  Pranab  63242.80  2013-07-30  Operations
7   8    Guru  72422.50  2014-06-17     Finance

In [9]:
df3[0:3]['name']

0     Rick
1      Dan
2    Tusar
Name: name, dtype: object

In [12]:
df3.loc[:,['start_date','dept']]   #to read all rows(loc[:,])

start_date        dept
0  2012-01-01          IT
1  2013-09-23  Operations
2  2014-11-15          IT
3  2014-05-11          HR
4  2015-03-27     Finance
5  2013-05-21          IT
6  2013-07-30  Operations
7  2014-06-17     Finance

In [13]:
df3.loc[[2,3,7],['salary','name']]

salary   name
2  61421.0  Tusar
3  72439.0   Ryan
7  72422.5   Guru

In [14]:
df3.loc[3:5,['salary','name']]

salary   name
3  72439.00   Ryan
4  84533.25   Gary
5  57638.00  Rasmi